### ISSUE TITLE
require appdata

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flathub#4]
Of the currently built 4 applications, only gnome-recipes has appdata, so it is the only one that shows up in gnome-software.

I think that is confusing, and we should make appdata a hard requirement for apps.

**Comment by TingPing** [comment]
All of mine have appdata.

**Comment by matthiasclasen** [comment]
Looking at

com.uploadedlobster.peek
com.vinszent.GnomeTwitch
io.github.Pithos        
org.freedesktop.GlxInfo

**Comment by matthiasclasen** [comment]
not much concrete action here, I've put it in the nascent review guidelines
