### ISSUE TITLE
Alternative to branches

### ISSUE THREAD

**Issue by jurf** [flatpak/flathub#5]
I’m still not sure whether branches are the correct way to do things, so I’d like to present the way the AUR is organised:
 * register once on their site
 * create a new package by issuing git clone git.aur.blah._package-name_
 * add build files into the cloned repo, push

More info on that [here](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages).

Advantages:
 * useful for maintainers of different modules, you can easily switch between them since they are in different folders by default
 * much easier for newcomers to contribute
 * much easier for maintainers to update stuff without having write access to everything
 * tried and tested

How we could make it suit Flathub:
 * we could use on OpenID (e.g. GitHub) to prevent spam, ease stuff for newcomers
 * new flatpaks would have to be manually checked and sent to the buildbot to ensure quality, prevent malicious builds, etc.

**Comment by alexlarsson** [comment]
Yeah, i was thinking about that too. Fedora uses repo-per-packaged too, and so does debian (typically, not all packages are in git). It is also a more natural flow for a user of the github UI, as it is based one working with repos, not branches.

So, today i created a new flathub organization: https://github.com/flathub 
I want to look at how it could work if we make each package a repo in that. It will be a bit more tricky to create a new repo (you need to set up some stuff with buildbot), but after that things will be more streamlined.

**Comment by jurf** [comment]
How do you want to manage PRs?

**Comment by jurf** [comment]
Also as I look at those commits you need find a better way to trigger rebuilds.

**Comment by alexlarsson** [comment]
There will be better ways to trigger rebuilds, but atm i'm hacking on the handling of changes, so i need events from github...

**Comment by jurf** [comment]
What about the PRs however?

**Comment by alexlarsson** [comment]
What about the PRs? I don't really understand the question.

**Comment by alexlarsson** [comment]
One nice thing about separate repos is that we can assign separate permissions for each app.

**Comment by jurf** [comment]
How to handle requests for new flatpaks.

**Comment by alexlarsson** [comment]
I guess you can file an issue to create a new repo, and then file a PR against the empty one. Or maybe a PR against a template repo. I'm sure we can figure something out.
Then the admins can run some scripts to create the repo.

**Comment by TingPing** [comment]
This can probably be closed since we have our own org. I do believe we should move the package requests to the flathub org rather than keeping them here though.

**Comment by Barthalion** [comment]
There is also Alex's [buildbot](https://github.com/alexlarsson/flathub-buildbot) repository, which probablt should be moved as well.

**Comment by matthiasclasen** [comment]
Lets close this now, yes
